"""Initial migration.

Revision ID: 743a05b491fb
Revises: 
Create Date: 2024-11-11 00:56:41.632154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a05b491fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('event_location', sa.String(length=100), nullable=False),
    sa.Column('traumatic_event', sa.String(length=200), nullable=False),
    sa.Column('scenario', sa.String(length=200), nullable=False),
    sa.Column('openness', sa.Integer(), nullable=False),
    sa.Column('conscientiousness', sa.Integer(), nullable=False),
    sa.Column('extraversion', sa.Integer(), nullable=False),
    sa.Column('agreeableness', sa.Integer(), nullable=False),
    sa.Column('neuroticism', sa.Integer(), nullable=False),
    sa.Column('additional_features', sa.Text(), nullable=True),
    sa.Column('improvise', sa.Boolean(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case')
    # ### end Alembic commands ###
